name: CI build

on:
  push:
  release:
    types:
      - created

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include: 
          - os: windows-2019
            auto_update: true
            ARTIFACT_NAME: YUView-Win.zip
    steps:
    - name: Debug wix
      run: |
        cd "C:\Program Files (x86)\Common Files\Merge Modules"
        cd
        dir "C:\Program Files (x86)\Common Files\Merge Modules"
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\"
        cd
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\"
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist"
        dir
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC"
        cd
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC"
      shell: cmd
    
  # How to upload files to the release:
  # https://github.com/Blacksmoke16/oq/pull/47/files#diff-082c28d748ad2e3eecc5508d740d9417R9-R29
  # Mime type list
  # https://www.iana.org/assignments/media-types/media-types.xhtml
